#!/bin/sh

NAME=nping

GATEWAY=$2
TARGET_IP=213.73.89.123
INTERFACE=br0
COUNT=40
RATE=4   # 10 packets/sec
WARNING=10 #percent
CRITICAL=25 #percent
MODE=icmp

while getopts ":H:C:i:I:w:c:" opt; do
  case "$opt" in
    H) GATEWAY=$OPTARG ;;
    C) COUNT=$OPTARG ;;
    i) RATE=$OPTARG ;;
    I) INTERFACE=$OPTARG ;;
    w) WARNING=$OPTARG ;;
    c) CRITICAL=$OPTARG ;;
    m) MODE=$OPTARG ;;
  esac
done

print_exit()
{
	echo -n "$NAME check: ${2}: "
		echo "$3" | tail -n 1 | sed -e 's/|//g'
		exit $1
}

MAC=`ping -c1 $GATEWAY >/dev/null; /usr/sbin/arp $GATEWAY | tail -n1 | awk '{print $3}'`
OUTPUT="`sudo /usr/bin/nping --rate $RATE --count $COUNT --$MODE --dest-mac $MAC -e $INTERFACE $TARGET_IP | grep 'Raw packets'`"
res=`echo $OUTPUT | awk '{print $12}'` 

if [ "$(($res*100/$COUNT))" -ge $CRITICAL ]; then
	print_exit 2 "CRITICAL" "$OUTPUT"
fi

if [ "$(($res*100/$COUNT))" -ge $WARNING ]; then
	print_exit 1 "WARNING" "$OUTPUT"
fi

if [ "$res" -lt $WARNING ]; then
	print_exit 0 "OK" "$OUTPUT"
fi

print_exit 3 "Unknown: $OUTPUT"
